language: cpp

compiler:
  - gcc

notifications:
    email:
        recipients:
            - max.sagebaum@scicomp.uni-kl.de
            - tim.albring@scicomp.uni-kl.de
        on_success: never
        on_failure: always
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

script: 
  - cd tests/
  - make 
